ListeMot = [
 {'mot': 'abandon', 'motTraduit': 'abandonment'},
 {'mot': 'abandonne', 'motTraduit': 'abandoned'},
 {'mot': 'abandonner', 'motTraduit': 'to abandon'},
 {'mot': 'accepte', 'motTraduit': 'accepted'},
 {'mot': 'accepter', 'motTraduit': 'accept'},
 {'mot': 'accompagne', 'motTraduit': 'accompanied'},
 {'mot': 'accompagner', 'motTraduit': 'to accompany'},
 {'mot': 'accord', 'motTraduit': 'OK'},
 {'mot': 'acheter', 'motTraduit': 'to buy'},
 {'mot': 'adore', 'motTraduit': 'love'},
 {'mot': 'adorer', 'motTraduit': 'love'},
 {'mot': 'agent', 'motTraduit': 'agent'},
 {'mot': 'agi', 'motTraduit': 'act'},
 {'mot': 'agir', 'motTraduit': 'to act'},
 {'mot': 'ai', 'motTraduit': 'have'},
 {'mot': 'aide', 'motTraduit': 'assistance'},
 {'mot': 'aider', 'motTraduit': 'to help'},
 {'mot': 'ail', 'motTraduit': 'garlic'},
 {'mot': 'aille', 'motTraduit': 'wing'},
 {'mot': 'aime', 'motTraduit': 'love'},
 {'mot': 'aimer', 'motTraduit': 'to like'},
 {'mot': 'air', 'motTraduit': 'air'},
 {'mot': 'aire', 'motTraduit': 'area'},
 {'mot': 'ais', 'motTraduit': 'ais'},
 {'mot': 'ait', 'motTraduit': 'has'},
 {'mot': 'ajout', 'motTraduit': 'addition'},
 {'mot': 'ajoute', 'motTraduit': 'add'},
 {'mot': 'ajouter', 'motTraduit': 'to add'},
 {'mot': 'aller', 'motTraduit': 'go'},
 {'mot': 'amen', 'motTraduit': 'Amen'},
 {'mot': 'amener', 'motTraduit': 'to bring'},
 {'mot': 'ami', 'motTraduit': 'friend'},
 {'mot': 'amour', 'motTraduit': 'love'},
 {'mot': 'amuser', 'motTraduit': 'amuse'},
 {'mot': 'ancien', 'motTraduit': 'ancient'},
 {'mot': 'ange', 'motTraduit': 'angel'},
 {'mot': 'année', 'motTraduit': 'year'},
 {'mot': 'annonce', 'motTraduit': 'announcement'},
 {'mot': 'annoncer', 'motTraduit': 'announce'},
 {'mot': 'ans', 'motTraduit': 'year'},
 {'mot': 'anse', 'motTraduit': 'handle'},
 {'mot': 'ante', 'motTraduit': 'ante'},
 {'mot': 'apercevoir', 'motTraduit': 'to notice'},
 {'mot': 'apparaît', 'motTraduit': 'appears'},
 {'mot': 'apparaître', 'motTraduit': 'appear'},
 {'mot': 'appel', 'motTraduit': 'call'},
 {'mot': 'appeler', 'motTraduit': 'to call'},
 {'mot': 'apport', 'motTraduit': 'bring'},
 {'mot': 'apporte', 'motTraduit': 'brought'},
 {'mot': 'apporter', 'motTraduit': 'to bring'},
 {'mot': 'apprend', 'motTraduit': 'learn'},
 {'mot': 'apprendre', 'motTraduit': 'learn'},
 {'mot': 'approche', 'motTraduit': 'approach'},
 {'mot': 'approcher', 'motTraduit': 'approach'},
 {'mot': 'arbre', 'motTraduit': 'tree'},
 {'mot': 'arc', 'motTraduit': 'bow'},
 {'mot': 'arche', 'motTraduit': 'ark'},
 {'mot': 'argent', 'motTraduit': 'silver'},
 {'mot': 'arme', 'motTraduit': 'armed'},
 {'mot': 'armé', 'motTraduit': 'armed'},
 {'mot': 'armée', 'motTraduit': 'army'},
 {'mot': 'arranger', 'motTraduit': 'arrange'},
 {'mot': 'arrêt', 'motTraduit': 'stop'},
 {'mot': 'arrête', 'motTraduit': 'stopped'},
 {'mot': 'arrêter', 'motTraduit': 'Stop'},
 {'mot': 'arrive', 'motTraduit': 'arrived'},
 {'mot': 'arriver', 'motTraduit': 'to arrive'},
 {'mot': 'art', 'motTraduit': 'art'},
 {'mot': 'asse', 'motTraduit': 'ASSE'},
 {'mot': 'assure', 'motTraduit': 'insure'},
 {'mot': 'assurer', 'motTraduit': 'to assure'},
 {'mot': 'attaque', 'motTraduit': 'offensive'},
 {'mot': 'attaquer', 'motTraduit': 'tackle'},
 {'mot': 'atteindre', 'motTraduit': 'reach'},
 {'mot': 'attend', 'motTraduit': 'waits'},
 {'mot': 'attendre', 'motTraduit': 'expect'},
 {'mot': 'attention', 'motTraduit': 'Warning'},
 {'mot': 'au', 'motTraduit': 'to'},
 {'mot': 'autre', 'motTraduit': 'other'},
 {'mot': 'aux', 'motTraduit': 'to'},
 {'mot': 'avance', 'motTraduit': 'advance'},
 {'mot': 'avancer', 'motTraduit': 'to advance'},
 {'mot': 'avenir', 'motTraduit': 'coming'},
 {'mot': 'averse', 'motTraduit': 'downpour'},
 {'mot': 'avion', 'motTraduit': 'plane'},
 {'mot': 'avis', 'motTraduit': 'notice'},
 {'mot': 'avoir', 'motTraduit': 'have'},
 {'mot': 'baisse', 'motTraduit': 'decrease'},
 {'mot': 'baisser', 'motTraduit': 'to lower'},
 {'mot': 'bal', 'motTraduit': 'ball'},
 {'mot': 'balle', 'motTraduit': 'ball'},
 {'mot': 'ban', 'motTraduit': 'ban'},
 {'mot': 'bat', 'motTraduit': 'bat'},
 {'mot': 'bateau', 'motTraduit': 'boat'},
 {'mot': 'battre', 'motTraduit': 'to beat'},
 {'mot': 'beau', 'motTraduit': 'beautiful'},
 {'mot': 'bébé', 'motTraduit': 'baby'},
 {'mot': 'besoin', 'motTraduit': 'need'},
 {'mot': 'bit', 'motTraduit': 'bit'},
 {'mot': 'bizarre', 'motTraduit': 'weird'},
 {'mot': 'blanc', 'motTraduit': 'White'},
 {'mot': 'bleu', 'motTraduit': 'blue'},
 {'mot': 'boire', 'motTraduit': 'to drink'},
 {'mot': 'bois', 'motTraduit': 'wood'},
 {'mot': 'bon', 'motTraduit': 'Well'},
 {'mot': 'bonheur', 'motTraduit': 'happiness'},
 {'mot': 'bonjour', 'motTraduit': 'hello'},
 {'mot': 'bonne', 'motTraduit': 'good'},
 {'mot': 'bord', 'motTraduit': 'edge'},
 {'mot': 'bouc', 'motTraduit': 'goat'},
 {'mot': 'bouche', 'motTraduit': 'stuffy'},
 {'mot': 'bouge', 'motTraduit': 'move'},
 {'mot': 'bouger', 'motTraduit': 'to move'},
 {'mot': 'boulot', 'motTraduit': 'gig'},
 {'mot': 'bout', 'motTraduit': 'end'},
 {'mot': 'bras', 'motTraduit': 'arms'},
 {'mot': 'bru', 'motTraduit': 'rude'},
 {'mot': 'bruit', 'motTraduit': 'noise'},
 {'mot': 'brûler', 'motTraduit': 'burn'},
 {'mot': 'bu', 'motTraduit': 'drank'},
 {'mot': 'bure', 'motTraduit': 'bure'},
 {'mot': 'bureau', 'motTraduit': 'desk'},
 {'mot': 'but', 'motTraduit': 'aim'},
 {'mot': 'cache', 'motTraduit': 'hidden'},
 {'mot': 'cacher', 'motTraduit': 'to hide'},
 {'mot': 'café', 'motTraduit': 'coffee'},
 {'mot': 'cal', 'motTraduit': 'cal'},
 {'mot': 'calme', 'motTraduit': 'calm'},
 {'mot': 'calmer', 'motTraduit': 'calm'},
 {'mot': 'camp', 'motTraduit': 'camp'},
 {'mot': 'cap', 'motTraduit': 'cap'},
 {'mot': 'capitaine', 'motTraduit': 'captain'},
 {'mot': 'car', 'motTraduit': 'because'},
 {'mot': 'carte', 'motTraduit': 'map'},
 {'mot': 'cas', 'motTraduit': 'case'},
 {'mot': 'casse', 'motTraduit': 'broken'},
 {'mot': 'casser', 'motTraduit': 'to break'},
 {'mot': 'cause', 'motTraduit': 'cause'},
 {'mot': 'ce', 'motTraduit': 'this'},
 {'mot': 'cendre', 'motTraduit': 'ash'},
 {'mot': 'cep', 'motTraduit': 'cep'},
 {'mot': 'certain', 'motTraduit': 'certain'},
 {'mot': 'ces', 'motTraduit': 'these'},
 {'mot': 'cesse', 'motTraduit': 'stop'},
 {'mot': 'cesser', 'motTraduit': 'to cease'},
 {'mot': 'chambre', 'motTraduit': 'bedroom'},
 {'mot': 'chance', 'motTraduit': 'chance'},
 {'mot': 'change', 'motTraduit': 'exchange'},
 {'mot': 'changer', 'motTraduit': 'to change'},
 {'mot': 'chant', 'motTraduit': 'song'},
 {'mot': 'chante', 'motTraduit': 'sung'},
 {'mot': 'chanter', 'motTraduit': 'to sing'},
 {'mot': 'char', 'motTraduit': 'tank'},
 {'mot': 'charge', 'motTraduit': 'charge'},
 {'mot': 'charger', 'motTraduit': 'load'},
 {'mot': 'chat', 'motTraduit': 'cat'},
 {'mot': 'chaud', 'motTraduit': 'hot'},
 {'mot': 'chef', 'motTraduit': 'chief'},
 {'mot': 'chemin', 'motTraduit': 'path'},
 {'mot': 'cher', 'motTraduit': 'dear'},
 {'mot': 'cherche', 'motTraduit': 'look for'},
 {'mot': 'chercher', 'motTraduit': 'look for'},
 {'mot': 'chéri', 'motTraduit': 'Dear'},
 {'mot': 'cheval', 'motTraduit': 'horse'},
 {'mot': 'cheveu', 'motTraduit': 'hair'},
 {'mot': 'chien', 'motTraduit': 'dog'},
 {'mot': 'choisi', 'motTraduit': 'selected'},
 {'mot': 'choisir', 'motTraduit': 'Choose'},
 {'mot': 'choix', 'motTraduit': 'choice'},
 {'mot': 'chose', 'motTraduit': 'thing'},
 {'mot': 'ciel', 'motTraduit': 'sky'},
 {'mot': 'cil', 'motTraduit': 'eyelash'},
 {'mot': 'clair', 'motTraduit': 'light'},
 {'mot': 'classe', 'motTraduit': 'class'},
 {'mot': 'client', 'motTraduit': 'customer'},
 {'mot': 'coi', 'motTraduit': 'COL'},
 {'mot': 'coin', 'motTraduit': 'corner'},
 {'mot': 'col', 'motTraduit': 'collar'},
 {'mot': 'colonel', 'motTraduit': 'colonel'},
 {'mot': 'comme', 'motTraduit': 'as'},
 {'mot': 'commence', 'motTraduit': 'begin'},
 {'mot': 'commencer', 'motTraduit': 'begin'},
 {'mot': 'commun', 'motTraduit': 'common'},
 {'mot': 'communs', 'motTraduit': 'common'},
 {'mot': 'compagne', 'motTraduit': 'companion'},
 {'mot': 'comprend', 'motTraduit': 'understand'},
 {'mot': 'comprendre', 'motTraduit': 'to understand'},
 {'mot': 'compte', 'motTraduit': 'account'},
 {'mot': 'compter', 'motTraduit': 'count'},
 {'mot': 'con', 'motTraduit': 'stupid'},
 {'mot': 'conduire', 'motTraduit': 'conduct'},
 {'mot': 'confiance', 'motTraduit': 'trust'},
 {'mot': 'connaît', 'motTraduit': 'know'},
 {'mot': 'connaître', 'motTraduit': 'to know'},
 {'mot': 'conte', 'motTraduit': 'tale'},
 {'mot': 'content', 'motTraduit': 'happy'},
 {'mot': 'conter', 'motTraduit': 'tell'},
 {'mot': 'continu', 'motTraduit': 'continued'},
 {'mot': 'continue', 'motTraduit': 'keep on going'},
 {'mot': 'continuer', 'motTraduit': 'Continue'},
 {'mot': 'contre', 'motTraduit': 'versus'},
 {'mot': 'contrer', 'motTraduit': 'to counter'},
 {'mot': 'copain', 'motTraduit': 'buddy'},
 {'mot': 'cor', 'motTraduit': 'horn'},
 {'mot': 'corps', 'motTraduit': 'body'},
 {'mot': 'côté', 'motTraduit': 'side'},
 {'mot': 'cou', 'motTraduit': 'neck'},
 {'mot': 'couche', 'motTraduit': 'layer'},
 {'mot': 'coucher', 'motTraduit': 'to sleep'},
 {'mot': 'coule', 'motTraduit': 'flow'},
 {'mot': 'couleur', 'motTraduit': 'color'},
 {'mot': 'coup', 'motTraduit': 'cut'},
 {'mot': 'coupe', 'motTraduit': 'chopped off'},
 {'mot': 'couper', 'motTraduit': 'to cut'},
 {'mot': 'cour', 'motTraduit': 'court'},
 {'mot': 'courant', 'motTraduit': 'running'},
 {'mot': 'courir', 'motTraduit': 'to run'},
 {'mot': 'cours', 'motTraduit': 'Classes'},
 {'mot': 'couvrir', 'motTraduit': 'cover'},
 {'mot': 'craindre', 'motTraduit': 'to fear'},
 {'mot': 'cri', 'motTraduit': 'shout'},
 {'mot': 'crie', 'motTraduit': 'calls out'},
 {'mot': 'crier', 'motTraduit': 'yell'},
 {'mot': 'croire', 'motTraduit': 'to believe'},
 {'mot': 'cuisine', 'motTraduit': 'kitchen'},
 {'mot': 'dam', 'motTraduit': 'damper'},
 {'mot': 'dame', 'motTraduit': 'lady'},
 {'mot': 'dans', 'motTraduit': 'in'},
 {'mot': 'danse', 'motTraduit': 'dance'},
 {'mot': 'danser', 'motTraduit': 'to dance'},
 {'mot': 'de', 'motTraduit': 'of'},
 {'mot': 'début', 'motTraduit': 'beginning'},
 {'mot': 'décide', 'motTraduit': 'decided'},
 {'mot': 'décider', 'motTraduit': 'decide'},
 {'mot': 'découvrir', 'motTraduit': 'discover'},
 {'mot': 'dégage', 'motTraduit': 'clear'},
 {'mot': 'dégager', 'motTraduit': 'clear'},
 {'mot': 'demande', 'motTraduit': 'request'},
 {'mot': 'demander', 'motTraduit': 'ask'},
 {'mot': 'dent', 'motTraduit': 'tooth'},
 {'mot': 'départ', 'motTraduit': 'departure'},
 {'mot': 'dernier', 'motTraduit': 'last'},
 {'mot': 'des', 'motTraduit': 'of the'},
 {'mot': 'descendre', 'motTraduit': 'to come down'},
 {'mot': 'désolé', 'motTraduit': 'sorry'},
 {'mot': 'désoler', 'motTraduit': 'desolate'},
 {'mot': 'déteste', 'motTraduit': 'hated'},
 {'mot': 'détester', 'motTraduit': 'to hate'},
 {'mot': 'détruire', 'motTraduit': 'destroy'},
 {'mot': 'devenir', 'motTraduit': 'become'},
 {'mot': 'devine', 'motTraduit': 'guess'},
 {'mot': 'deviner', 'motTraduit': 'to guess'},
 {'mot': 'devoir', 'motTraduit': 'to have to'},
 {'mot': 'dieu', 'motTraduit': 'god'},
 {'mot': 'différent', 'motTraduit': 'different'},
 {'mot': 'difficile', 'motTraduit': 'hard'},
 {'mot': 'dire', 'motTraduit': 'say'},
 {'mot': 'dis', 'motTraduit': 'say'},
 {'mot': 'disparaît', 'motTraduit': 'disappears'},
 {'mot': 'disparaître', 'motTraduit': 'vanish'},
 {'mot': 'docteur', 'motTraduit': 'doctor'},
 {'mot': 'doigt', 'motTraduit': 'finger'},
 {'mot': 'dollar', 'motTraduit': 'dollar'},
 {'mot': 'don', 'motTraduit': 'Don'},
 {'mot': 'donne', 'motTraduit': 'given'},
 {'mot': 'donner', 'motTraduit': 'give'},
 {'mot': 'dorer', 'motTraduit': 'brown'},
 {'mot': 'dormir', 'motTraduit': 'sleep'},
 {'mot': 'doute', 'motTraduit': 'doubt'},
 {'mot': 'doux', 'motTraduit': 'soft'},
 {'mot': 'droit', 'motTraduit': 'right'},
 {'mot': 'droite', 'motTraduit': 'right'},
 {'mot': 'drôle', 'motTraduit': 'funny'},
 {'mot': 'du', 'motTraduit': 'from'},
 {'mot': 'eau', 'motTraduit': 'water'},
 {'mot': 'échappe', 'motTraduit': 'escape'},
 {'mot': 'échapper', 'motTraduit': 'escape'},
 {'mot': 'école', 'motTraduit': 'school'},
 {'mot': 'écoute', 'motTraduit': 'listen'},
 {'mot': 'écouter', 'motTraduit': 'to listen'},
 {'mot': 'écrire', 'motTraduit': 'to write'},
 {'mot': 'écu', 'motTraduit': 'shield'},
 {'mot': 'effet', 'motTraduit': 'effect'},
 {'mot': 'église', 'motTraduit': 'church'},
 {'mot': 'éloigner', 'motTraduit': 'remove'},
 {'mot': 'embrasse', 'motTraduit': 'kiss'},
 {'mot': 'embrasser', 'motTraduit': 'embrace'},
 {'mot': 'emmener', 'motTraduit': 'to take'},
 {'mot': 'empêche', 'motTraduit': 'stop'},
 {'mot': 'empêcher', 'motTraduit': 'to prevent'},
 {'mot': 'emporte', 'motTraduit': 'take away'},
 {'mot': 'emporter', 'motTraduit': 'carry'},
 {'mot': 'en', 'motTraduit': 'in'},
 {'mot': 'encontre', 'motTraduit': 'against'},
 {'mot': 'end', 'motTraduit': 'ending'},
 {'mot': 'endroit', 'motTraduit': 'place'},
 {'mot': 'enfant', 'motTraduit': 'child'},
 {'mot': 'enlever', 'motTraduit': 'to remove'},
 {'mot': 'ennemi', 'motTraduit': 'enemy'},
 {'mot': 'entend', 'motTraduit': 'hears'},
 {'mot': 'entendre', 'motTraduit': 'To hear'},
 {'mot': 'entier', 'motTraduit': 'entire'},
 {'mot': 'entre', 'motTraduit': 'Between'},
 {'mot': 'entrer', 'motTraduit': 'walk in'},
 {'mot': 'envi', 'motTraduit': 'envy'},
 {'mot': 'envie', 'motTraduit': 'urge'},
 {'mot': 'envoyer', 'motTraduit': 'send'},
 {'mot': 'épaule', 'motTraduit': 'shoulder'},
 {'mot': 'époque', 'motTraduit': 'era'},
 {'mot': 'équipe', 'motTraduit': 'crew'},
 {'mot': 'ère', 'motTraduit': 'time'},
 {'mot': 'errer', 'motTraduit': 'wander'},
 {'mot': 'erreur', 'motTraduit': 'mistake'},
 {'mot': 'escalier', 'motTraduit': 'stairs'},
 {'mot': 'espèce', 'motTraduit': 'species'},
 {'mot': 'espérer', 'motTraduit': 'to hope'},
 {'mot': 'esprit', 'motTraduit': 'spirit'},
 {'mot': 'essayer', 'motTraduit': 'try'},
 {'mot': 'est', 'motTraduit': 'is'},
 {'mot': 'et', 'motTraduit': 'and'},
 {'mot': 'état', 'motTraduit': 'state'},
 {'mot': 'étrange', 'motTraduit': 'odd'},
 {'mot': 'être', 'motTraduit': 'be'},
 {'mot': 'eux', 'motTraduit': 'them'},
 {'mot': 'éveiller', 'motTraduit': 'awake'},
 {'mot': 'évite', 'motTraduit': 'avoid'},
 {'mot': 'éviter', 'motTraduit': 'to avoid'},
 {'mot': 'excuse', 'motTraduit': 'excuse'},
 {'mot': 'excuser', 'motTraduit': 'excuse'},
 {'mot': 'exemple', 'motTraduit': 'example'},
 {'mot': 'existe', 'motTraduit': 'exist'},
 {'mot': 'exister', 'motTraduit': 'to exist'},
 {'mot': 'explique', 'motTraduit': 'Explain'},
 {'mot': 'expliquer', 'motTraduit': 'explain'},
 {'mot': 'fac', 'motTraduit': 'college'},
 {'mot': 'face', 'motTraduit': 'face'},
 {'mot': 'facile', 'motTraduit': 'easy'},
 {'mot': 'façon', 'motTraduit': 'way'},
 {'mot': 'faim', 'motTraduit': 'hunger'},
 {'mot': 'fait', 'motTraduit': 'do'},
 {'mot': 'falloir', 'motTraduit': 'to need'},
 {'mot': 'famille', 'motTraduit': 'family'},
 {'mot': 'fan', 'motTraduit': 'fan'},
 {'mot': 'faut', 'motTraduit': 'should'},
 {'mot': 'faute', 'motTraduit': 'mistake'},
 {'mot': 'faux', 'motTraduit': 'fake'},
 {'mot': 'femme', 'motTraduit': 'women'},
 {'mot': 'fer', 'motTraduit': 'iron'},
 {'mot': 'ferme', 'motTraduit': 'closed'},
 {'mot': 'fermer', 'motTraduit': 'close'},
 {'mot': 'fête', 'motTraduit': 'Party'},
 {'mot': 'fil', 'motTraduit': 'thread'},
 {'mot': 'file', 'motTraduit': 'line'},
 {'mot': 'filer', 'motTraduit': 'spin'},
 {'mot': 'fille', 'motTraduit': 'daughter'},
 {'mot': 'film', 'motTraduit': 'film'},
 {'mot': 'fils', 'motTraduit': 'son'},
 {'mot': 'fin', 'motTraduit': 'end'},
 {'mot': 'fini', 'motTraduit': 'finished'},
 {'mot': 'finir', 'motTraduit': 'finish'},
 {'mot': 'fléchir', 'motTraduit': 'flex'},
 {'mot': 'fleur', 'motTraduit': 'flower'},
 {'mot': 'flic', 'motTraduit': 'cop'},
 {'mot': 'foi', 'motTraduit': 'faith'},
 {'mot': 'fois', 'motTraduit': 'time'},
 {'mot': 'fond', 'motTraduit': 'bottom'},
 {'mot': 'for', 'motTraduit': 'for'},
 {'mot': 'force', 'motTraduit': 'strength'},
 {'mot': 'forme', 'motTraduit': 'form'},
 {'mot': 'fort', 'motTraduit': 'strong'},
 {'mot': 'fou', 'motTraduit': 'mad'},
 {'mot': 'foutre', 'motTraduit': 'cum'},
 {'mot': 'français', 'motTraduit': 'French'},
 {'mot': 'frappe', 'motTraduit': 'struck'},
 {'mot': 'frapper', 'motTraduit': 'to hit'},
 {'mot': 'frère', 'motTraduit': 'brother'},
 {'mot': 'froid', 'motTraduit': 'cold'},
 {'mot': 'front', 'motTraduit': 'forehead'},
 {'mot': 'fus', 'motTraduit': 'was'},
 {'mot': 'gage', 'motTraduit': 'pledge'},
 {'mot': 'gager', 'motTraduit': 'pledge'},
 {'mot': 'gagne', 'motTraduit': 'won'},
 {'mot': 'gagner', 'motTraduit': 'to win'},
 {'mot': 'garçon', 'motTraduit': 'boy'},
 {'mot': 'garde', 'motTraduit': 'keep'},
 {'mot': 'garder', 'motTraduit': 'To keep'},
 {'mot': 'gars', 'motTraduit': 'guys'},
 {'mot': 'gauche', 'motTraduit': 'left'},
 {'mot': 'général', 'motTraduit': 'general'},
 {'mot': 'genre', 'motTraduit': 'gender'},
 {'mot': 'gens', 'motTraduit': 'people'},
 {'mot': 'gentil', 'motTraduit': 'kindly'},
 {'mot': 'geste', 'motTraduit': 'gesture'},
 {'mot': 'glisse', 'motTraduit': 'slide'},
 {'mot': 'glisser', 'motTraduit': 'slide'},
 {'mot': 'gosse', 'motTraduit': 'kid'},
 {'mot': 'goût', 'motTraduit': 'taste'},
 {'mot': 'gouvernement', 'motTraduit': 'government'},
 {'mot': 'grand', 'motTraduit': 'big'},
 {'mot': 'grave', 'motTraduit': 'severe'},
 {'mot': 'gros', 'motTraduit': 'big'},
 {'mot': 'group', 'motTraduit': 'group'},
 {'mot': 'groupe', 'motTraduit': 'band'},
 {'mot': 'guerre', 'motTraduit': 'war'},
 {'mot': 'gueule', 'motTraduit': 'mouth'},
 {'mot': 'habite', 'motTraduit': 'reside'},
 {'mot': 'habiter', 'motTraduit': 'to live in'},
 {'mot': 'habitude', 'motTraduit': 'habit'},
 {'mot': 'han', 'motTraduit': 'han'},
 {'mot': 'hante', 'motTraduit': 'haunted'},
 {'mot': 'happe', 'motTraduit': 'hape'},
 {'mot': 'happer', 'motTraduit': 'hape'},
 {'mot': 'haut', 'motTraduit': 'high'},
 {'mot': 'heure', 'motTraduit': 'hour'},
 {'mot': 'heureux', 'motTraduit': 'happy'},
 {'mot': 'histoire', 'motTraduit': 'story'},
 {'mot': 'homme', 'motTraduit': 'man'},
 {'mot': 'honneur', 'motTraduit': 'honor'},
 {'mot': 'hôte', 'motTraduit': 'host'},
 {'mot': 'hôtel', 'motTraduit': 'hotel'},
 {'mot': 'humain', 'motTraduit': 'human'},
 {'mot': 'ici', 'motTraduit': 'here'},
 {'mot': 'idée', 'motTraduit': 'idea'},
 {'mot': 'ignore', 'motTraduit': 'ignore'},
 {'mot': 'ignorer', 'motTraduit': 'ignore'},
 {'mot': 'il', 'motTraduit': 'he'},
 {'mot': 'ils', 'motTraduit': 'they'},
 {'mot': 'image', 'motTraduit': 'image'},
 {'mot': 'imagine', 'motTraduit': 'conceived'},
 {'mot': 'imaginer', 'motTraduit': 'to imagine'},
 {'mot': 'import', 'motTraduit': 'import'},
 {'mot': 'important', 'motTraduit': 'important'},
 {'mot': 'importe', 'motTraduit': 'imported'},
 {'mot': 'importer', 'motTraduit': 'import'},
 {'mot': 'impossible', 'motTraduit': 'impossible'},
 {'mot': 'impression', 'motTraduit': 'impression'},
 {'mot': 'inquiéter', 'motTraduit': 'worry'},
 {'mot': 'installer', 'motTraduit': 'install'},
 {'mot': 'instant', 'motTraduit': 'moment'},
 {'mot': 'intéresse', 'motTraduit': 'interested'},
 {'mot': 'intéresser', 'motTraduit': 'to interest'},
 {'mot': 'intérêt', 'motTraduit': 'interest'},
 {'mot': 'intérieur', 'motTraduit': 'interior'},
 {'mot': 'invite', 'motTraduit': 'guest'},
 {'mot': 'inviter', 'motTraduit': 'invite'},
 {'mot': 'ion', 'motTraduit': 'ion'},
 {'mot': 'ivre', 'motTraduit': 'drunk'},
 {'mot': 'jambe', 'motTraduit': 'leg'},
 {'mot': 'jardin', 'motTraduit': 'garden'},
 {'mot': 'je', 'motTraduit': 'I'},
 {'mot': 'jet', 'motTraduit': 'jet'},
 {'mot': 'jeter', 'motTraduit': 'to throw'},
 {'mot': 'jeu', 'motTraduit': 'Game'},
 {'mot': 'jeun', 'motTraduit': 'fasting'},
 {'mot': 'jeune', 'motTraduit': 'young'},
 {'mot': 'joie', 'motTraduit': 'joy'},
 {'mot': 'joindre', 'motTraduit': 'join'},
 {'mot': 'joli', 'motTraduit': 'attractive'},
 {'mot': 'joue', 'motTraduit': 'play'},
 {'mot': 'jouer', 'motTraduit': 'to play'},
 {'mot': 'jour', 'motTraduit': 'day'},
 {'mot': 'journal', 'motTraduit': 'log'},
 {'mot': 'journée', 'motTraduit': 'daytime'},
 {'mot': 'jure', 'motTraduit': 'sworn'},
 {'mot': 'jurer', 'motTraduit': 'swear'},
 {'mot': 'jus', 'motTraduit': 'juice'},
 {'mot': 'juste', 'motTraduit': 'just'},
 {'mot': 'la', 'motTraduit': 'the'},
 {'mot': 'lac', 'motTraduit': 'lake'},
 {'mot': 'lâche', 'motTraduit': 'cowardly'},
 {'mot': 'lâcher', 'motTraduit': 'let go'},
 {'mot': 'laisse', 'motTraduit': 'leave alone'},
 {'mot': 'laisser', 'motTraduit': 'let'},
 {'mot': 'lance', 'motTraduit': 'spear'},
 {'mot': 'lancer', 'motTraduit': 'throw'},
 {'mot': 'langue', 'motTraduit': 'language'},
 {'mot': 'las', 'motTraduit': 'the ace'},
 {'mot': 'lasse', 'motTraduit': 'weary'},
 {'mot': 'le', 'motTraduit': 'the'},
 {'mot': 'léger', 'motTraduit': 'light'},
 {'mot': 'lettre', 'motTraduit': 'letter'},
 {'mot': 'leur', 'motTraduit': 'their'},
 {'mot': 'lever', 'motTraduit': 'lift'},
 {'mot': 'lèvre', 'motTraduit': 'lip'},
 {'mot': 'libre', 'motTraduit': 'free'},
 {'mot': 'lice', 'motTraduit': 'loss'},
 {'mot': 'lie', 'motTraduit': 'related'},
 {'mot': 'lien', 'motTraduit': 'link'},
 {'mot': 'lier', 'motTraduit': 'bind'},
 {'mot': 'lieu', 'motTraduit': 'venue'},
 {'mot': 'ligne', 'motTraduit': 'line'},
 {'mot': 'lion', 'motTraduit': 'lion'},
 {'mot': 'lire', 'motTraduit': 'read'},
 {'mot': 'lis', 'motTraduit': 'Lily'},
 {'mot': 'lisse', 'motTraduit': 'smooth'},
 {'mot': 'lisser', 'motTraduit': 'smooth'},
 {'mot': 'livre', 'motTraduit': 'book'},
 {'mot': 'loi', 'motTraduit': 'law'},
 {'mot': 'loir', 'motTraduit': 'loyalty'},
 {'mot': 'long', 'motTraduit': 'long'},
 {'mot': 'lot', 'motTraduit': 'batch'},
 {'mot': 'lu', 'motTraduit': 'read'},
 {'mot': 'lumière', 'motTraduit': 'light'},
 {'mot': 'ma', 'motTraduit': 'my'},
 {'mot': 'madame', 'motTraduit': 'madam'},
 {'mot': 'mai', 'motTraduit': 'may'},
 {'mot': 'main', 'motTraduit': 'hand'},
 {'mot': 'maintenir', 'motTraduit': 'maintain'},
 {'mot': 'mais', 'motTraduit': 'but'},
 {'mot': 'maison', 'motTraduit': 'home'},
 {'mot': 'maître', 'motTraduit': 'master'},
 {'mot': 'mal', 'motTraduit': 'wrong'},
 {'mot': 'malade', 'motTraduit': 'sick'},
 {'mot': 'maman', 'motTraduit': 'mom'},
 {'mot': 'mander', 'motTraduit': 'unite'},
 {'mot': 'mange', 'motTraduit': 'eat'},
 {'mot': 'manger', 'motTraduit': 'to eat'},
 {'mot': 'manière', 'motTraduit': 'way'},
 {'mot': 'manque', 'motTraduit': 'lack'},
 {'mot': 'manquer', 'motTraduit': 'to lack'},
 {'mot': 'marche', 'motTraduit': 'walking'},
 {'mot': 'marcher', 'motTraduit': 'walk'},
 {'mot': 'mari', 'motTraduit': 'husband'},
 {'mot': 'maria', 'motTraduit': 'Maria'},
 {'mot': 'mariage', 'motTraduit': 'wedding'},
 {'mot': 'marie', 'motTraduit': 'married'},
 {'mot': 'marier', 'motTraduit': 'marry'},
 {'mot': 'marque', 'motTraduit': 'Mark'},
 {'mot': 'marquer', 'motTraduit': 'to mark'},
 {'mot': 'matin', 'motTraduit': 'morning'},
 {'mot': 'mauvais', 'motTraduit': 'Wrong'},
 {'mot': 'médecin', 'motTraduit': 'doctor'},
 {'mot': 'meilleur', 'motTraduit': 'better'},
 {'mot': 'même', 'motTraduit': 'same'},
 {'mot': 'mener', 'motTraduit': 'carry out'},
 {'mot': 'mentir', 'motTraduit': 'lie'},
 {'mot': 'mer', 'motTraduit': 'sea'},
 {'mot': 'merci', 'motTraduit': 'thank you'},
 {'mot': 'merde', 'motTraduit': 'shit'},
 {'mot': 'mère', 'motTraduit': 'mother'},
 {'mot': 'met', 'motTraduit': 'put'},
 {'mot': 'mètre', 'motTraduit': 'metre'},
 {'mot': 'mettre', 'motTraduit': 'put'},
 {'mot': 'mie', 'motTraduit': 'crumb'},
 {'mot': 'mil', 'motTraduit': 'millet'},
 {'mot': 'milieu', 'motTraduit': 'environment'},
 {'mot': 'mille', 'motTraduit': 'thousand'},
 {'mot': 'million', 'motTraduit': 'million'},
 {'mot': 'min', 'motTraduit': 'min'},
 {'mot': 'mine', 'motTraduit': 'mine'},
 {'mot': 'minute', 'motTraduit': 'minute'},
 {'mot': 'moi', 'motTraduit': 'me'},
 {'mot': 'mois', 'motTraduit': 'month'},
 {'mot': 'moment', 'motTraduit': 'moment'},
 {'mot': 'mon', 'motTraduit': 'my'},
 {'mot': 'monde', 'motTraduit': 'world'},
 {'mot': 'monsieur', 'motTraduit': 'sir'},
 {'mot': 'mont', 'motTraduit': 'Mountain'},
 {'mot': 'monte', 'motTraduit': 'mounted'},
 {'mot': 'monter', 'motTraduit': 'ascend'},
 {'mot': 'montre', 'motTraduit': 'show'},
 {'mot': 'montrer', 'motTraduit': 'to show'},
 {'mot': 'mort', 'motTraduit': 'dead'},
 {'mot': 'mou', 'motTraduit': 'soft'},
 {'mot': 'mourir', 'motTraduit': 'die'},
 {'mot': 'mouvement', 'motTraduit': 'movement'},
 {'mot': 'moyen', 'motTraduit': 'medium'},
 {'mot': 'musique', 'motTraduit': 'music'},
 {'mot': 'naît', 'motTraduit': 'arise'},
 {'mot': 'naître', 'motTraduit': 'be born'},
 {'mot': 'né', 'motTraduit': 'born'},
 {'mot': 'née', 'motTraduit': 'born'},
 {'mot': 'ni', 'motTraduit': 'neither'},
 {'mot': 'nie', 'motTraduit': 'nie'},
 {'mot': 'nier', 'motTraduit': 'deny'},
 {'mot': 'noir', 'motTraduit': 'black'},
 {'mot': 'non', 'motTraduit': 'Nope'},
 {'mot': 'nonce', 'motTraduit': 'nuncio'},
 {'mot': 'nouveau', 'motTraduit': 'new'},
 {'mot': 'nu', 'motTraduit': 'naked'},
 {'mot': 'nue', 'motTraduit': 'naked'},
 {'mot': 'nuit', 'motTraduit': 'night'},
 {'mot': 'numéro', 'motTraduit': 'number'},
 {'mot': 'oblige', 'motTraduit': 'obligatory'},
 {'mot': 'obliger', 'motTraduit': 'obligate'},
 {'mot': 'occupe', 'motTraduit': 'to keep busy'},
 {'mot': 'occuper', 'motTraduit': 'to occupy'},
 {'mot': 'odeur', 'motTraduit': 'odour'},
 {'mot': 'oeil', 'motTraduit': 'eye'},
 {'mot': 'offrir', 'motTraduit': 'to offer'},
 {'mot': 'oie', 'motTraduit': 'goose'},
 {'mot': 'oindre', 'motTraduit': 'anoint'},
 {'mot': 'oiseau', 'motTraduit': 'bird'},
 {'mot': 'ombre', 'motTraduit': 'shadow'},
 {'mot': 'omettre', 'motTraduit': 'omit'},
 {'mot': 'on', 'motTraduit': 'we'},
 {'mot': 'once', 'motTraduit': 'ounce'},
 {'mot': 'oncle', 'motTraduit': 'uncle'},
 {'mot': 'onde', 'motTraduit': 'wave'},
 {'mot': 'one', 'motTraduit': 'One One'},
 {'mot': 'ont', 'motTraduit': 'have'},
 {'mot': 'or', 'motTraduit': 'gold'},
 {'mot': 'ordre', 'motTraduit': 'order'},
 {'mot': 'oreille', 'motTraduit': 'ear'},
 {'mot': 'os', 'motTraduit': 'bone'},
 {'mot': 'ose', 'motTraduit': 'dare'},
 {'mot': 'oser', 'motTraduit': 'to dare'},
 {'mot': 'ou', 'motTraduit': 'Where'},
 {'mot': 'oubli', 'motTraduit': 'oversight'},
 {'mot': 'oublie', 'motTraduit': 'forget'},
 {'mot': 'oublier', 'motTraduit': 'to forget'},
 {'mot': 'ouf', 'motTraduit': 'phew'},
 {'mot': 'ours', 'motTraduit': 'bear'},
 {'mot': 'outre', 'motTraduit': 'outraged'},
 {'mot': 'ouvrir', 'motTraduit': 'open'},
 {'mot': 'pain', 'motTraduit': 'bread'},
 {'mot': 'paix', 'motTraduit': 'peace'},
 {'mot': 'papa', 'motTraduit': 'father'},
 {'mot': 'papier', 'motTraduit': 'paper'},
 {'mot': 'par', 'motTraduit': 'by'},
 {'mot': 'paraît', 'motTraduit': 'appears'},
 {'mot': 'paraître', 'motTraduit': 'appear'},
 {'mot': 'pare', 'motTraduit': 'bare'},
 {'mot': 'pareil', 'motTraduit': 'the same'},
 {'mot': 'parent', 'motTraduit': 'parent'},
 {'mot': 'parer', 'motTraduit': 'adorn'},
 {'mot': 'parle', 'motTraduit': 'speak'},
 {'mot': 'parler', 'motTraduit': 'talk'},
 {'mot': 'parole', 'motTraduit': 'word'},
 {'mot': 'part', 'motTraduit': 'go'},
 {'mot': 'parti', 'motTraduit': 'left'},
 {'mot': 'partie', 'motTraduit': 'part'},
 {'mot': 'partir', 'motTraduit': 'leave'},
 {'mot': 'pas', 'motTraduit': 'not'},
 {'mot': 'passa', 'motTraduit': 'passed'},
 {'mot': 'passage', 'motTraduit': 'passage'},
 {'mot': 'passe', 'motTraduit': 'pass'},
 {'mot': 'passé', 'motTraduit': 'past'},
 {'mot': 'passer', 'motTraduit': 'pass'},
 {'mot': 'patron', 'motTraduit': 'boss'},
 {'mot': 'pauvre', 'motTraduit': 'poor'},
 {'mot': 'paye', 'motTraduit': 'paid'},
 {'mot': 'payer', 'motTraduit': 'pay'},
 {'mot': 'pays', 'motTraduit': 'country'},
 {'mot': 'peau', 'motTraduit': 'skin'},
 {'mot': 'pêche', 'motTraduit': 'sin'},
 {'mot': 'pêcher', 'motTraduit': 'to fish'},
 {'mot': 'peine', 'motTraduit': 'sadness'},
 {'mot': 'peler', 'motTraduit': 'peel'},
 {'mot': 'pense', 'motTraduit': 'think'},
 {'mot': 'pensé', 'motTraduit': 'think'},
 {'mot': 'pensée', 'motTraduit': 'thought'},
 {'mot': 'penser', 'motTraduit': 'think'},
 {'mot': 'percevoir', 'motTraduit': 'perceive'},
 {'mot': 'perd', 'motTraduit': 'lose'},
 {'mot': 'perdre', 'motTraduit': 'to lose'},
 {'mot': 'père', 'motTraduit': 'dad'},
 {'mot': 'perm', 'motTraduit': 'Perm'},
 {'mot': 'perme', 'motTraduit': 'allow'},
 {'mot': 'permet', 'motTraduit': 'allow'},
 {'mot': 'permettre', 'motTraduit': 'allow'},
 {'mot': 'personne', 'motTraduit': 'nobody'},
 {'mot': 'petit', 'motTraduit': 'little'},
 {'mot': 'peu', 'motTraduit': 'little'},
 {'mot': 'peuple', 'motTraduit': 'people'},
 {'mot': 'peur', 'motTraduit': 'fear'},
 {'mot': 'photo', 'motTraduit': 'Photo'},
 {'mot': 'pie', 'motTraduit': 'sparkle'},
 {'mot': 'pièce', 'motTraduit': 'room'},
 {'mot': 'pied', 'motTraduit': 'foot'},
 {'mot': 'pierre', 'motTraduit': 'stone'},
 {'mot': 'place', 'motTraduit': 'square'},
 {'mot': 'plaire', 'motTraduit': 'to please'},
 {'mot': 'plaisir', 'motTraduit': 'pleasure'},
 {'mot': 'plan', 'motTraduit': 'plan'},
 {'mot': 'plein', 'motTraduit': 'full'},
 {'mot': 'pleure', 'motTraduit': 'cry'},
 {'mot': 'pleurer', 'motTraduit': 'cry'},
 {'mot': 'pli', 'motTraduit': 'fold'},
 {'mot': 'pluriel', 'motTraduit': 'plural'},
 {'mot': 'poche', 'motTraduit': 'poached'},
 {'mot': 'point', 'motTraduit': 'point'},
 {'mot': 'poli', 'motTraduit': 'polite'},
 {'mot': 'police', 'motTraduit': 'police'},
 {'mot': 'port', 'motTraduit': 'port'},
 {'mot': 'porta', 'motTraduit': 'carried'},
 {'mot': 'portant', 'motTraduit': 'wearing'},
 {'mot': 'porte', 'motTraduit': 'gate'},
 {'mot': 'porter', 'motTraduit': 'carry'},
 {'mot': 'pose', 'motTraduit': 'laid'},
 {'mot': 'poser', 'motTraduit': 'to pose'},
 {'mot': 'possible', 'motTraduit': 'possible'},
 {'mot': 'pou', 'motTraduit': 'pou'},
 {'mot': 'pousse', 'motTraduit': 'growth'},
 {'mot': 'pousser', 'motTraduit': 'to push'},
 {'mot': 'pouvoir', 'motTraduit': 'power'},
 {'mot': 'pré', 'motTraduit': 'pre'},
 {'mot': 'préférer', 'motTraduit': 'prefer'},
 {'mot': 'premier', 'motTraduit': 'first'},
 {'mot': 'prend', 'motTraduit': 'take'},
 {'mot': 'prendre', 'motTraduit': 'take'},
 {'mot': 'prépare', 'motTraduit': 'prepared'},
 {'mot': 'préparer', 'motTraduit': 'to prepare'},
 {'mot': 'prés', 'motTraduit': 'close'},
 {'mot': 'présence', 'motTraduit': 'presence'},
 {'mot': 'présent', 'motTraduit': 'here'},
 {'mot': 'présente', 'motTraduit': 'present'},
 {'mot': 'présenter', 'motTraduit': 'to present'},
 {'mot': 'préside', 'motTraduit': 'chairmanship'},
 {'mot': 'président', 'motTraduit': 'President'},
 {'mot': 'pression', 'motTraduit': 'pressure'},
 {'mot': 'prêt', 'motTraduit': 'ready'},
 {'mot': 'prévenir', 'motTraduit': 'prevent'},
 {'mot': 'prie', 'motTraduit': 'pray'},
 {'mot': 'prier', 'motTraduit': 'pray'},
 {'mot': 'prince', 'motTraduit': 'prince'},
 {'mot': 'pris', 'motTraduit': 'taken'},
 {'mot': 'prison', 'motTraduit': 'jail'},
 {'mot': 'prit', 'motTraduit': 'taken'},
 {'mot': 'prix', 'motTraduit': 'price'},
 {'mot': 'pro', 'motTraduit': 'pro'},
 {'mot': 'problème', 'motTraduit': 'problem'},
 {'mot': 'prochain', 'motTraduit': 'next'},
 {'mot': 'proche', 'motTraduit': 'close'},
 {'mot': 'prof', 'motTraduit': 'teacher'},
 {'mot': 'professeur', 'motTraduit': 'teacher'},
 {'mot': 'promet', 'motTraduit': 'promise'},
 {'mot': 'promettre', 'motTraduit': 'to promise'},
 {'mot': 'propos', 'motTraduit': 'about'},
 {'mot': 'propose', 'motTraduit': 'offers'},
 {'mot': 'proposer', 'motTraduit': 'to propose'},
 {'mot': 'propre', 'motTraduit': 'own'},
 {'mot': 'protéger', 'motTraduit': 'protect'},
 {'mot': 'pu', 'motTraduit': 'could'},
 {'mot': 'putain', 'motTraduit': 'whore'},
 {'mot': 'quart', 'motTraduit': 'quarter'},
 {'mot': 'quartier', 'motTraduit': 'piece'},
 {'mot': 'que', 'motTraduit': 'that'},
 {'mot': 'question', 'motTraduit': 'question'},
 {'mot': 'qui', 'motTraduit': 'who'},
 {'mot': 'quitte', 'motTraduit': 'quits'},
 {'mot': 'quitter', 'motTraduit': 'leave'},
 {'mot': 'quoi', 'motTraduit': 'what'},
 {'mot': 'raconte', 'motTraduit': 'recount'},
 {'mot': 'raconter', 'motTraduit': 'to tell about'},
 {'mot': 'rai', 'motTraduit': 'rai'},
 {'mot': 'raison', 'motTraduit': 'reason'},
 {'mot': 'rame', 'motTraduit': 'row'},
 {'mot': 'ramener', 'motTraduit': 'to bring back'},
 {'mot': 'rang', 'motTraduit': 'rank'},
 {'mot': 'range', 'motTraduit': 'tidy'},
 {'mot': 'ranger', 'motTraduit': 'tidy'},
 {'mot': 'rappel', 'motTraduit': 'reminder'},
 {'mot': 'rappeler', 'motTraduit': 'recall'},
 {'mot': 'rapport', 'motTraduit': 'report'},
 {'mot': 'recevoir', 'motTraduit': 'receive'},
 {'mot': 'reconnaît', 'motTraduit': 'recognize'},
 {'mot': 'reconnaître', 'motTraduit': 'recognize'},
 {'mot': 'référer', 'motTraduit': 'refer'},
 {'mot': 'réfléchi', 'motTraduit': 'reflexive'},
 {'mot': 'réfléchir', 'motTraduit': 'reflect'},
 {'mot': 'refus', 'motTraduit': 'refusal'},
 {'mot': 'refuse', 'motTraduit': 'denied'},
 {'mot': 'refuser', 'motTraduit': 'to refuse'},
 {'mot': 'regard', 'motTraduit': 'glance'},
 {'mot': 'regarde', 'motTraduit': 'looked'},
 {'mot': 'regarder', 'motTraduit': 'to look at'},
 {'mot': 'rejoindre', 'motTraduit': 'rejoin'},
 {'mot': 'remarque', 'motTraduit': 'remark'},
 {'mot': 'remarquer', 'motTraduit': 'to remark'},
 {'mot': 'remet', 'motTraduit': 'put back'},
 {'mot': 'remettre', 'motTraduit': 'to put back'},
 {'mot': 'remonte', 'motTraduit': 'traced back'},
 {'mot': 'remonter', 'motTraduit': 'go back up'},
 {'mot': 'rencontre', 'motTraduit': 'meet'},
 {'mot': 'rencontrer', 'motTraduit': 'to encounter'},
 {'mot': 'rend', 'motTraduit': 'renders'},
 {'mot': 'rendre', 'motTraduit': 'to return'},
 {'mot': 'rentre', 'motTraduit': 'go home'},
 {'mot': 'rentrer', 'motTraduit': 'to return'},
 {'mot': 'réparer', 'motTraduit': 'to fix'},
 {'mot': 'répéter', 'motTraduit': 'repeat'},
 {'mot': 'répond', 'motTraduit': 'respond'},
 {'mot': 'répondre', 'motTraduit': 'answer'},
 {'mot': 'réponse', 'motTraduit': 'answer'},
 {'mot': 'repos', 'motTraduit': 'rest'},
 {'mot': 'repose', 'motTraduit': 'rests'},
 {'mot': 'reposer', 'motTraduit': 'to rest'},
 {'mot': 'reprend', 'motTraduit': 'resumes'},
 {'mot': 'reprendre', 'motTraduit': 'to resume'},
 {'mot': 'réside', 'motTraduit': 'resides'},
 {'mot': 'résident', 'motTraduit': 'resident'},
 {'mot': 'ressemble', 'motTraduit': 'looks like'},
 {'mot': 'ressembler', 'motTraduit': 'look like'},
 {'mot': 'reste', 'motTraduit': 'rest'},
 {'mot': 'rester', 'motTraduit': 'stay'},
 {'mot': 'retard', 'motTraduit': 'delay'},
 {'mot': 'retenir', 'motTraduit': 'to hold onto'},
 {'mot': 'retire', 'motTraduit': 'took of'},
 {'mot': 'retirer', 'motTraduit': 'remove'},
 {'mot': 'retour', 'motTraduit': 'return'},
 {'mot': 'retourne', 'motTraduit': 'return'},
 {'mot': 'retourner', 'motTraduit': 'flip'},
 {'mot': 'retrouve', 'motTraduit': 'find'},
 {'mot': 'retrouver', 'motTraduit': 'to regain'},
 {'mot': 'réussi', 'motTraduit': 'successful'},
 {'mot': 'réussir', 'motTraduit': 'to succeed'},
 {'mot': 'rêve', 'motTraduit': 'dream'},
 {'mot': 'réveil', 'motTraduit': 'awakening'},
 {'mot': 'réveille', 'motTraduit': 'wake up'},
 {'mot': 'réveiller', 'motTraduit': 'wake'},
 {'mot': 'revenir', 'motTraduit': 'come back'},
 {'mot': 'rêver', 'motTraduit': 'dream'},
 {'mot': 'revoir', 'motTraduit': 'see again'},
 {'mot': 'ri', 'motTraduit': 'laughed'},
 {'mot': 'rire', 'motTraduit': 'laugh'},
 {'mot': 'risque', 'motTraduit': 'risk'},
 {'mot': 'risquer', 'motTraduit': 'risk'},
 {'mot': 'rit', 'motTraduit': 'laugh'},
 {'mot': 'rive', 'motTraduit': 'shore'},
 {'mot': 'robe', 'motTraduit': 'dress'},
 {'mot': 'roc', 'motTraduit': 'rock'},
 {'mot': 'roche', 'motTraduit': 'rock'},
 {'mot': 'rocher', 'motTraduit': 'rock'},
 {'mot': 'roi', 'motTraduit': 'King'},
 {'mot': 'rôle', 'motTraduit': 'role'},
 {'mot': 'rom', 'motTraduit': 'roma'},
 {'mot': 'rouge', 'motTraduit': 'red'},
 {'mot': 'roule', 'motTraduit': 'rolled'},
 {'mot': 'rouler', 'motTraduit': 'to roll'},
 {'mot': 'route', 'motTraduit': 'road'},
 {'mot': 'sa', 'motTraduit': 'her'},
 {'mot': 'sage', 'motTraduit': 'wise'},
 {'mot': 'sale', 'motTraduit': 'dirty'},
 {'mot': 'salle', 'motTraduit': 'Hall'},
 {'mot': 'salut', 'motTraduit': 'Hello'},
 {'mot': 'sang', 'motTraduit': 'blood'},
 {'mot': 'saut', 'motTraduit': 'jump'},
 {'mot': 'saute', 'motTraduit': 'jumped up'},
 {'mot': 'sauter', 'motTraduit': 'skip'},
 {'mot': 'sauve', 'motTraduit': 'Safe'},
 {'mot': 'sauver', 'motTraduit': 'save'},
 {'mot': 'scène', 'motTraduit': 'stage'},
 {'mot': 'seau', 'motTraduit': 'bucket'},
 {'mot': 'sec', 'motTraduit': 'dry'},
 {'mot': 'second', 'motTraduit': 'second'},
 {'mot': 'seconde', 'motTraduit': 'second'},
 {'mot': 'secret', 'motTraduit': 'secret'},
 {'mot': 'sécurité', 'motTraduit': 'security'},
 {'mot': 'seigneur', 'motTraduit': 'lord'},
 {'mot': 'semaine', 'motTraduit': 'week'},
 {'mot': 'semble', 'motTraduit': 'seems'},
 {'mot': 'sembler', 'motTraduit': 'seem'},
 {'mot': 'sens', 'motTraduit': 'meaning'},
 {'mot': 'sent', 'motTraduit': 'feel'},
 {'mot': 'sente', 'motTraduit': 'feel'},
 {'mot': 'senti', 'motTraduit': 'felt'},
 {'mot': 'sentiment', 'motTraduit': 'feeling'},
 {'mot': 'sentir', 'motTraduit': 'feel'},
 {'mot': 'seoir', 'motTraduit': 'seal'},
 {'mot': 'sépare', 'motTraduit': 'separate'},
 {'mot': 'séparer', 'motTraduit': 'to separate'},
 {'mot': 'série', 'motTraduit': 'series'},
 {'mot': 'sérieux', 'motTraduit': 'serious'},
 {'mot': 'serre', 'motTraduit': 'tight'},
 {'mot': 'serrer', 'motTraduit': 'to squeeze'},
 {'mot': 'servi', 'motTraduit': 'served'},
 {'mot': 'service', 'motTraduit': 'service'},
 {'mot': 'servir', 'motTraduit': 'to serve'},
 {'mot': 'seul', 'motTraduit': 'only'},
 {'mot': 'si', 'motTraduit': 'if'},
 {'mot': 'siècle', 'motTraduit': 'century'},
 {'mot': 'signe', 'motTraduit': 'sign'},
 {'mot': 'silence', 'motTraduit': 'silence'},
 {'mot': 'simple', 'motTraduit': 'simple'},
 {'mot': 'sine', 'motTraduit': 'sine'},
 {'mot': 'sir', 'motTraduit': 'sir'},
 {'mot': 'situation', 'motTraduit': 'situation'},
 {'mot': 'soeur', 'motTraduit': 'sister'},
 {'mot': 'soi', 'motTraduit': 'self'},
 {'mot': 'soin', 'motTraduit': 'care'},
 {'mot': 'soir', 'motTraduit': 'evening'},
 {'mot': 'soirée', 'motTraduit': 'evening'},
 {'mot': 'sol', 'motTraduit': 'floor'},
 {'mot': 'soldat', 'motTraduit': 'soldier'},
 {'mot': 'soleil', 'motTraduit': 'Sun'},
 {'mot': 'son', 'motTraduit': 'his'},
 {'mot': 'sonne', 'motTraduit': 'sound'},
 {'mot': 'sort', 'motTraduit': 'spell'},
 {'mot': 'sorte', 'motTraduit': 'sort'},
 {'mot': 'sorti', 'motTraduit': 'got out'},
 {'mot': 'sortir', 'motTraduit': 'go out'},
 {'mot': 'sou', 'motTraduit': 'soup'},
 {'mot': 'souffrir', 'motTraduit': 'suffer'},
 {'mot': 'sourire', 'motTraduit': 'smile'},
 {'mot': 'souvenir', 'motTraduit': 'memory'},
 {'mot': 'stalle', 'motTraduit': 'stall'},
 {'mot': 'su', 'motTraduit': 'known'},
 {'mot': 'suffi', 'motTraduit': 'sufficient'},
 {'mot': 'suffire', 'motTraduit': 'suffice'},
 {'mot': 'suit', 'motTraduit': 'follows'},
 {'mot': 'suite', 'motTraduit': 'after'},
 {'mot': 'suivre', 'motTraduit': 'follow'},
 {'mot': 'sujet', 'motTraduit': 'topic'},
 {'mot': 'super', 'motTraduit': 'Great'},
 {'mot': 'sur', 'motTraduit': 'on'},
 {'mot': 'ta', 'motTraduit': 'your'},
 {'mot': 'table', 'motTraduit': 'table'},
 {'mot': 'tain', 'motTraduit': 'tain'},
 {'mot': 'taire', 'motTraduit': 'to hush up'},
 {'mot': 'tant', 'motTraduit': 'so much'},
 {'mot': 'tard', 'motTraduit': 'late'},
 {'mot': 'teindre', 'motTraduit': 'dye'},
 {'mot': 'tel', 'motTraduit': 'Phone'},
 {'mot': 'télé', 'motTraduit': 'TV'},
 {'mot': 'téléphone', 'motTraduit': 'telephone'},
 {'mot': 'temps', 'motTraduit': 'time'},
 {'mot': 'tend', 'motTraduit': 'tend'},
 {'mot': 'tendre', 'motTraduit': 'tender'},
 {'mot': 'tenir', 'motTraduit': 'hold'},
 {'mot': 'tente', 'motTraduit': 'attempted'},
 {'mot': 'tenter', 'motTraduit': 'to attempt'},
 {'mot': 'termine', 'motTraduit': 'ended'},
 {'mot': 'terminer', 'motTraduit': 'to end'},
 {'mot': 'terre', 'motTraduit': 'earth'},
 {'mot': 'tes', 'motTraduit': 'your'},
 {'mot': 'test', 'motTraduit': 'test'},
 {'mot': 'tester', 'motTraduit': 'test'},
 {'mot': 'tête', 'motTraduit': 'head'},
 {'mot': 'tir', 'motTraduit': 'shot'},
 {'mot': 'tire', 'motTraduit': 'drawn'},
 {'mot': 'tirer', 'motTraduit': 'pull'},
 {'mot': 'toi', 'motTraduit': 'you'},
 {'mot': 'tom', 'motTraduit': 'Tom'},
 {'mot': 'tombe', 'motTraduit': 'falls'},
 {'mot': 'tomber', 'motTraduit': 'to fall'},
 {'mot': 'touche', 'motTraduit': 'touches'},
 {'mot': 'toucher', 'motTraduit': 'to touch'},
 {'mot': 'tour', 'motTraduit': 'round'},
 {'mot': 'tourne', 'motTraduit': 'turned'},
 {'mot': 'tourner', 'motTraduit': 'turn'},
 {'mot': 'tout', 'motTraduit': 'everything'},
 {'mot': 'train', 'motTraduit': 'train'},
 {'mot': 'traîne', 'motTraduit': 'dragged'},
 {'mot': 'traîner', 'motTraduit': 'hang out'},
 {'mot': 'trait', 'motTraduit': 'trait'},
 {'mot': 'traite', 'motTraduit': 'treaty'},
 {'mot': 'traiter', 'motTraduit': 'treat'},
 {'mot': 'tranquille', 'motTraduit': 'calm'},
 {'mot': 'travail', 'motTraduit': 'work'},
 {'mot': 'travaille', 'motTraduit': 'work'},
 {'mot': 'travailler', 'motTraduit': 'work'},
 {'mot': 'travers', 'motTraduit': 'through'},
 {'mot': 'traverse', 'motTraduit': 'crossing'},
 {'mot': 'traverser', 'motTraduit': 'to cross'},
 {'mot': 'tri', 'motTraduit': 'sorting'},
 {'mot': 'triste', 'motTraduit': 'sad'},
 {'mot': 'trompe', 'motTraduit': 'deceived'},
 {'mot': 'tromper', 'motTraduit': 'deceive'},
 {'mot': 'trou', 'motTraduit': 'hole'},
 {'mot': 'trouve', 'motTraduit': 'find'},
 {'mot': 'trouver', 'motTraduit': 'to find'},
 {'mot': 'truc', 'motTraduit': 'thing'},
 {'mot': 'tu', 'motTraduit': 'you'},
 {'mot': 'tue', 'motTraduit': 'kill'},
 {'mot': 'tuer', 'motTraduit': 'kill'},
 {'mot': 'type', 'motTraduit': 'kind'},
 {'mot': 'un', 'motTraduit': 'a'},
 {'mot': 'une', 'motTraduit': 'a'},
 {'mot': 'use', 'motTraduit': 'worn'},
 {'mot': 'user', 'motTraduit': 'use'},
 {'mot': 'utilise', 'motTraduit': 'used'},
 {'mot': 'utiliser', 'motTraduit': 'utilize'},
 {'mot': 'va', 'motTraduit': 'go'},
 {'mot': 'vaille', 'motTraduit': 'valiant'},
 {'mot': 'vais', 'motTraduit': 'go'},
 {'mot': 'val', 'motTraduit': 'valve'},
 {'mot': 'valoir', 'motTraduit': 'to be worth'},
 {'mot': 'van', 'motTraduit': 'van'},
 {'mot': 'veau', 'motTraduit': 'calf'},
 {'mot': 'veille', 'motTraduit': 'standby'},
 {'mot': 'veiller', 'motTraduit': 'watch'},
 {'mot': 'vend', 'motTraduit': 'sells'},
 {'mot': 'vendre', 'motTraduit': 'sale'},
 {'mot': 'venir', 'motTraduit': 'come'},
 {'mot': 'vent', 'motTraduit': 'wind'},
 {'mot': 'ventre', 'motTraduit': 'belly'},
 {'mot': 'ver', 'motTraduit': 'worm'},
 {'mot': 'vérité', 'motTraduit': 'truth'},
 {'mot': 'verne', 'motTraduit': 'verne'},
 {'mot': 'verre', 'motTraduit': 'glass'},
 {'mot': 'vers', 'motTraduit': 'towards'},
 {'mot': 'verse', 'motTraduit': 'pour'},
 {'mot': 'verser', 'motTraduit': 'to pay'},
 {'mot': 'vert', 'motTraduit': 'green'},
 {'mot': 'vice', 'motTraduit': 'vice'},
 {'mot': 'vide', 'motTraduit': 'empty'},
 {'mot': 'vie', 'motTraduit': 'life'},
 {'mot': 'vieux', 'motTraduit': 'old'},
 {'mot': 'vil', 'motTraduit': 'vile'},
 {'mot': 'villa', 'motTraduit': 'Villa'},
 {'mot': 'village', 'motTraduit': 'town'},
 {'mot': 'ville', 'motTraduit': 'town'},
 {'mot': 'vin', 'motTraduit': 'wine'},
 {'mot': 'vis', 'motTraduit': 'screw'},
 {'mot': 'visa', 'motTraduit': 'Visa'},
 {'mot': 'visage', 'motTraduit': 'face'},
 {'mot': 'vit', 'motTraduit': 'lives'},
 {'mot': 'vite', 'motTraduit': 'quick'},
 {'mot': 'vivant', 'motTraduit': 'living'},
 {'mot': 'vivre', 'motTraduit': 'live'},
 {'mot': 'voir', 'motTraduit': 'see'},
 {'mot': 'voit', 'motTraduit': 'sees'},
 {'mot': 'voiture', 'motTraduit': 'car'},
 {'mot': 'voix', 'motTraduit': 'voice'},
 {'mot': 'vol', 'motTraduit': 'flight'},
 {'mot': 'vole', 'motTraduit': 'Fly'},
 {'mot': 'voler', 'motTraduit': 'steal'},
 {'mot': 'vouloir', 'motTraduit': 'want to'},
 {'mot': 'voyage', 'motTraduit': 'travel'},
 {'mot': 'vrai', 'motTraduit': 'true'},
 {'mot': 'yen', 'motTraduit': 'yen'}]
